### ISSUE TITLE
Cant find AutoHotkey.dll

### ISSUE THREAD

**Issue by Anony12** [atomizer/starbreak-zoom#3]
Error: Could not find C:\Users\mark\Desktop\sb\AutoHotkey.dll library.
sbzoom.exe: Failed to inject AutoHotkey.dll into the game process.

**Comment by atomizer** [comment]
For anyone that has the same issue, try following:

- make sure that the path to the directory where `sbzoom.exe` is does not contain non-ascii symbols (anything other than latin A-Z, digits, punctuation)
- run sbzoom as admin
- check your antivirus logs if you have one, make sure sbzoom is whitelisted
- make sure that the game is NOT fullscreen _before_ you run sbzoom

**Comment by Anony12** [comment]
I've tried everything above including removing virusprogram(malwarebytes), reinstalling Steam and sbzoom and nothing works unfortunately. Fresh win7 Home edition with latest drivers from windows update. There's nothing on my computer as far as i can tell that would prevent it from working.

**Comment by Anony12** [comment]
It is working now for some reason. I dont know if this is the case but it might have had somthing to do with Java, after i reinstalled it sbzoom is working, apart from that the only changes i've done on my computer to my knowledge is installing 2 games.

**Comment by richtan** [comment]
That sometimes happens to me too. I just wait a bit and it works again.
